# Deployment and Service file for the mongo db
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  # How many pobs we wish to create using this blueprint
  replicas: 1 # Should only have 1 instance of db if we want more we should use a statefulset
  selector:
    # Selectors define how K8s know which pods belong to which deployments
    matchLabels:
      app: mongo
  # Configuration for the pod inside the deployment definition
  template:
    metadata:
      # In K8s you can give any component a key value pair label, which give information about the component
      # e.g. "release": "stable" "env": "dev" or "env": "production"
      # Different instances of the same pod have the same name, so labels facilitate a collective identifier  
      labels:
        app: mongo
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 8081
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef: 
              name: mongo-secret
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-pwd
--- # yaml syntax for multiple components within a single yaml file
# Service definition
# Services are used to expose groups of pods over a network
# Request -> Port 8080 (Service) -> forwarded to containerPort (8081)
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  # Services need to fwd the request from their endpoint, how does service know which to forward to? Uses the same label selector
  selector:
    app: mango
  ports:
  # Service is accessible within the K8s cluster using this address
    - protocol: TCP
      # I haven't done it here for clarity but it is a common standard to keep service port and container port the same to keep things simple
      port: 8080
      # This is the port of the pods, same as the container pod
      targetPort: 8081